sports = input("enter the name of sport")
fav_player = input("enter fav_player")
highest_score = int(input("enter score"))
print(5,end='---')
print(6,end='---')
print(7,'---')
print(sports)
print(f"your fav player is {fav_player}")
print(highest_score)
print()